In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os


here = os.path.abspath('') #get the current directory the python file is in, just place all teh other files in this folder

exfiltration_csv1_file= os.path.join(here, 'IOT_data_theft_0503_train_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df=pd.read_csv(exfiltration_csv1_file)
#df2=pd.read_csv(exfiltration_csv2_file)
#df3=pd.read_csv(os_scan_csv,sep=";")

In [2]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,Window,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack
0,0.000000,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,605,0x000,551.0,551.0,1024.0,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0
1,0.000245,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,653,NaN,NaN,NaN,NaN,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0
2,0.000248,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,752,0x000,698.0,698.0,1024.0,127.0,0x00,0x00,NaN,0.000248,0.000248,NaN,NaN,0
3,0.000251,192.168.100.46,80.0,UDP,192.168.100.5,80.0,702,NaN,NaN,NaN,NaN,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0
4,0.000254,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,790,NaN,NaN,NaN,NaN,127.0,0x00,0x00,NaN,NaN,NaN,0.000009,0.000009,0

In [3]:
#df['sport'][df['No.']].hist()

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299138 entries, 0 to 299137
Data columns (total 20 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               299138 non-null  float64
 1   saddr                                              299138 non-null  object
 2   sport                                              299073 non-null  float64
 3   Protocol                                           299138 non-null  object
 4   daddr                                              299138 non-null  object
 5   dport                                              299073 non-null  float64
 6   Length                                             299138 non-null  int64
 7   TCP_Flags                                          183592 non-null  object
 8   Bytes in flight                                    153469 non-null  float64
 9   Bytes sent since last PSH flag                     153469 non-null  float64
 10  Window                                             183592 non-null  float64
 11  Time to Live                                       299074 non-null  float64
 12  IPv4_frag_Flags                                    299074 non-null  object
 13  Differentiated Services Field                      299074 non-null  object
 14  The RTT to ACK the segment was                     29435 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     183592 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  183592 non-null  float64
 17  Time since first frame(UDP)                        115481 non-null  float64
 18  Time since previous frame(UDP)                     115481 non-null  float64
 19  Attack                                             299138 non-null  int64
dtypes: float64(12), int64(2), object(6)
memory usage: 45.6+ MB

In [4]:
df['Attack']

0         0
1         0
2         0
3         0
4         0
         ..
299133    0
299134    0
299135    0
299136    0
299137    0
Name: Attack, Length: 299138, dtype: int64

In [5]:
len(df)

299138

In [6]:
df.isnull().values.any()

True

In [7]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035 ':1,'IPv4':0, '0x86dd':6}
df['Protocol']=[protocol_vals[k] for k in df['Protocol']]

In [8]:
df['Protocol']

0         4
1         5
2         4
3         5
4         5
         ..
299133    4
299134    4
299135    4
299136    4
299137    4
Name: Protocol, Length: 299138, dtype: int64

In [9]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,Window,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,605,0x000,551.0,551.0,1024.0,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0
1,0.000245,192.168.100.46,3456.0,5,192.168.100.5,80.0,653,NaN,NaN,NaN,NaN,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0
2,0.000248,192.168.100.55,8080.0,4,192.168.100.3,80.0,752,0x000,698.0,698.0,1024.0,127.0,0x00,0x00,NaN,0.000248,0.000248,NaN,NaN,0
3,0.000251,192.168.100.46,80.0,5,192.168.100.5,80.0,702,NaN,NaN,NaN,NaN,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0
4,0.000254,192.168.100.5,80.0,5,192.168.100.46,3456.0,790,NaN,NaN,NaN,NaN,127.0,0x00,0x00,NaN,NaN,NaN,0.000009,0.000009,0

In [10]:


df['Window']=df['Window'].fillna(0)
df['dport']=df['dport'].fillna(0)
df['sport']=df['sport'].fillna(0)
df['TCP_Flags']=df['TCP_Flags'].fillna('0x000')
df['Bytes in flight']=df['Bytes in flight'].fillna(0)
df['Bytes sent since last PSH flag']=df['Bytes sent since last PSH flag'].fillna(0)
df['The RTT to ACK the segment was']=df['The RTT to ACK the segment was'].fillna(0)
df['Time since previous frame in this TCP stream(TCP)']=df['Time since previous frame in this TCP stream(TCP)'].fillna(0)
#df['Time to Live']=df['Time to Live'].fillna(0)

In [11]:
from ast import literal_eval
df['TCP_Flags']=[literal_eval(k) for k in df['TCP_Flags']]
#df.info()

In [12]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,Window,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,605,0,551.0,551.0,1024.0,127.0,0x00,0x00,0.0,0.000000,0.000000,NaN,NaN,0
1,0.000245,192.168.100.46,3456.0,5,192.168.100.5,80.0,653,0,0.0,0.0,0.0,127.0,0x00,0x00,0.0,NaN,0.000000,0.000000,0.000000,0
2,0.000248,192.168.100.55,8080.0,4,192.168.100.3,80.0,752,0,698.0,698.0,1024.0,127.0,0x00,0x00,0.0,0.000248,0.000248,NaN,NaN,0
3,0.000251,192.168.100.46,80.0,5,192.168.100.5,80.0,702,0,0.0,0.0,0.0,127.0,0x00,0x00,0.0,NaN,0.000000,0.000000,0.000000,0
4,0.000254,192.168.100.5,80.0,5,192.168.100.46,3456.0,790,0,0.0,0.0,0.0,127.0,0x00,0x00,0.0,NaN,0.000000,0.000009,0.000009,0

In [67]:
#import sklearn
#from sklearn.preprocessing import StandardScaler

In [13]:
#sc=StandardScaler()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 299138 entries, 0 to 299137
Data columns (total 20 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               299138 non-null  float64
 1   saddr                                              299138 non-null  object
 2   sport                                              299138 non-null  float64
 3   Protocol                                           299138 non-null  int64
 4   daddr                                              299138 non-null  object
 5   dport                                              299138 non-null  float64
 6   Length                                             299138 non-null  int64
 7   TCP_Flags                                          299138 non-null  int64
 8   Bytes in flight                                    299138 non-null  float64
 9   Bytes sent since last PSH flag                     299138 non-null  float64
 10  Window                                             299138 non-null  float64
 11  Time to Live                                       299074 non-null  float64
 12  IPv4_frag_Flags                                    299074 non-null  object
 13  Differentiated Services Field                      299074 non-null  object
 14  The RTT to ACK the segment was                     299138 non-null  float64
 15  Time since first frame in this TCP stream(TCP)     183592 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  299138 non-null  float64
 17  Time since first frame(UDP)                        115481 non-null  float64
 18  Time since previous frame(UDP)                     115481 non-null  float64
 19  Attack                                             299138 non-null  int64
dtypes: float64(12), int64(4), object(4)
memory usage: 45.6+ MB

In [14]:
X=df[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Bytes sent since last PSH flag','Time since previous frame in this TCP stream(TCP)']].values
Y=df['Attack'].values

In [15]:
X.shape

(299138, 9)

In [16]:
X

array([[8.0000000e+01, 8.0800000e+03, 4.0000000e+00, ..., 5.5100000e+02,
        5.5100000e+02, 0.0000000e+00],
       [3.4560000e+03, 8.0000000e+01, 5.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [8.0800000e+03, 8.0000000e+01, 4.0000000e+00, ..., 6.9800000e+02,
        6.9800000e+02, 2.4800000e-04],
       ...,
       [3.9260000e+04, 4.4300000e+02, 4.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 4.1454854e-02],
       [4.4300000e+02, 3.9260000e+04, 4.0000000e+00, ..., 1.5600000e+02,
        1.6160000e+03, 1.1215100e-04],
       [3.9260000e+04, 4.4300000e+02, 4.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 7.1644000e-05]])

In [17]:
import sklearn
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#X=sc.fit_transform(X)

scaler=sc.fit(X)
X=scaler.transform(X)

import pickle
pickle.dump(sc, open('exfiltration_scaler_.pkl','wb'))

In [230]:
#exfiltration_df=[[89090,8007,4,296,61024,6789,2429,14520565,0.040332]]
#packet_df_exfiltration=pd.DataFrame(exfiltration_df,columns=['sport','dport','Protocol','Length','window','TCP Flag','Bytes in flight','Bytes sent since last PSH flag','Time since previous frame in this TCP stream(TCP)'])
#exfiltration_df=scaler.transform(exfiltration_df)
#exfiltration_df

array([[ 5.88150489e+00, -3.94367566e-02, -7.91787637e-01,
        -2.29954178e-01,  2.60067916e+00,  8.26327505e+02,
         4.36117712e-02,  1.49102854e+00, -2.12211033e-02]])

In [18]:
#X=sc.transform(X)
#X=scaler.transform(X)
X

array([[-0.45108963, -0.03495995, -0.79178764, ..., -0.08430142,
        -0.57386917, -0.03664627],
       [-0.21090494, -0.52556931,  1.26033351, ..., -0.1218308 ,
        -0.57394753, -0.03664627],
       [ 0.1180684 , -0.52556931, -0.79178764, ..., -0.07428905,
        -0.57384826, -0.03655142],
       ...,
       [ 2.33636182, -0.50330791, -0.79178764, ..., -0.1218308 ,
        -0.57394753, -0.02079166],
       [-0.42526409,  1.87719006, -0.79178764, ..., -0.11120542,
        -0.57371771, -0.03660338],
       [ 2.33636182, -0.50330791, -0.79178764, ..., -0.1218308 ,
        -0.57394753, -0.03661887]])

In [19]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.25)

In [21]:
X_train

array([[-0.45678121, -0.53047541, -0.79178764, ..., -0.02429529,
         0.05336395, -0.03190077],
       [-0.45108963, -0.52556931,  1.26033351, ..., -0.1218308 ,
        -0.57394753, -0.03664627],
       [-0.14061393,  2.48431916, -0.79178764, ..., -0.1218308 ,
        -0.57394753, -0.0366436 ],
       ...,
       [ 3.44095526, -0.50330791, -0.79178764, ..., -0.1218308 ,
        -0.57394753, -0.03664258],
       [-0.45108963, -0.03495995, -0.79178764, ..., -0.02266061,
         0.69731235, -0.03664168],
       [-0.45108963, -0.03495995, -0.79178764, ..., -0.02266061,
         2.03360734, -0.03663862]])

In [22]:
from sklearn import svm
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.neural_network import MLPClassifier
from sklearn import tree

In [23]:
svm_model=svm.SVC()
adaboost_model=AdaBoostClassifier()
mlp_model=MLPClassifier(hidden_layer_sizes=(10,7,4))
decision_tree=tree.DecisionTreeClassifier()

In [24]:
svm_model.fit(X_train,Y_train)  #i am hereeeeeeeeeeeeeeeee dec 06

SVC()

In [25]:
adaboost_model.fit(X_train,Y_train)

AdaBoostClassifier()

In [26]:
#mlp_model=MLPClassifier(hidden_layer_sizes=(10,7,4))
mlp_model.fit(X_train,Y_train)

MLPClassifier(hidden_layer_sizes=(10, 7, 4))

In [27]:
decision_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [28]:
svm_model.score(X_test,Y_test)

0.9991174700808986

In [29]:
adaboost_model.score(X_test,Y_test)

0.9999465133382363

In [30]:
mlp_model.score(X_test,Y_test)

0.9998261683492679

In [31]:
decision_tree.score(X_test,Y_test)

0.9999331416727953

In [84]:
#now to import the second pcap file as test it
exfiltration_csv2_file= os.path.join(here, 'IOT_data_theft_1101.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df2=pd.read_csv(exfiltration_csv2_file)

In [85]:
df2.head()

,No.,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,...,Window,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack
0,1,0.000000,192.168.100.149,4444,TCP,192.168.100.6,49160,60,0x010,NaN,...,21216.0,64,0x40,0x00,NaN,0.000000,0.000000,NaN,NaN,1
1,2,0.000001,192.168.100.149,4444,TCP,192.168.100.6,49160,60,0x010,NaN,...,21167.0,64,0x40,0x00,NaN,0.000001,0.000001,NaN,NaN,1
2,3,0.000037,192.168.100.149,4444,TCP,192.168.100.6,49160,60,0x010,NaN,...,20985.0,64,0x40,0x00,NaN,0.000037,0.000036,NaN,NaN,1
3,4,0.000039,192.168.100.149,4444,TCP,192.168.100.6,49160,60,0x010,NaN,...,21216.0,64,0x40,0x00,NaN,0.000039,0.000002,NaN,NaN,1
4,5,0.000055,192.168.100.149,4444,TCP,192.168.100.6,49160,60,0x010,NaN,...,21216.0,64,0x40,0x00,NaN,0.000055,0.000016,NaN,NaN,1

In [86]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df2['Protocol']=[protocol_vals[k] for k in df2['Protocol']]

In [87]:
df2['Window']=df2['Window'].fillna(0)
df2['dport']=df2['dport'].fillna(0)
df2['sport']=df2['sport'].fillna(0)
df2['TCP_Flags']=df2['TCP_Flags'].fillna('0x000')
df2['Bytes in flight']=df2['Bytes in flight'].fillna(0)
df2['Bytes sent since last PSH flag']=df2['Bytes sent since last PSH flag'].fillna(0)
df2['The RTT to ACK the segment was']=df2['The RTT to ACK the segment was'].fillna(0)
df2['Time since previous frame in this TCP stream(TCP)']=df2['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [88]:
from ast import literal_eval
df2['TCP_Flags']=[literal_eval(k) for k in df2['TCP_Flags']]

In [89]:
X2=df2[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Bytes sent since last PSH flag','Time since previous frame in this TCP stream(TCP)']].values
Y2=df2['Attack'].values

In [90]:
df2.head()

,No.,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,...,Window,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack
0,1,0.000000,192.168.100.149,4444,4,192.168.100.6,49160,60,16,0.0,...,21216.0,64,0x40,0x00,0.0,0.000000,0.000000,NaN,NaN,1
1,2,0.000001,192.168.100.149,4444,4,192.168.100.6,49160,60,16,0.0,...,21167.0,64,0x40,0x00,0.0,0.000001,0.000001,NaN,NaN,1
2,3,0.000037,192.168.100.149,4444,4,192.168.100.6,49160,60,16,0.0,...,20985.0,64,0x40,0x00,0.0,0.000037,0.000036,NaN,NaN,1
3,4,0.000039,192.168.100.149,4444,4,192.168.100.6,49160,60,16,0.0,...,21216.0,64,0x40,0x00,0.0,0.000039,0.000002,NaN,NaN,1
4,5,0.000055,192.168.100.149,4444,4,192.168.100.6,49160,60,16,0.0,...,21216.0,64,0x40,0x00,0.0,0.000055,0.000016,NaN,NaN,1

In [91]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 65475 entries, 0 to 65474
Data columns (total 21 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   No.                                                65475 non-null  int64
 1   Time                                               65475 non-null  float64
 2   saddr                                              65475 non-null  object
 3   sport                                              65475 non-null  int64
 4   Protocol                                           65475 non-null  int64
 5   daddr                                              65475 non-null  object
 6   dport                                              65475 non-null  int64
 7   Length                                             65475 non-null  int64
 8   TCP_Flags                                          65475 non-null  int64
 9   Bytes in flight                                    65475 non-null  float64
 10  Bytes sent since last PSH flag                     65475 non-null  float64
 11  Window                                             65475 non-null  float64
 12  Time to Live                                       65475 non-null  int64
 13  IPv4_frag_Flags                                    65475 non-null  object
 14  Differentiated Services Field                      65475 non-null  object
 15  The RTT to ACK the segment was                     65475 non-null  float64
 16  Time since first frame in this TCP stream(TCP)     39745 non-null  float64
 17  Time since previous frame in this TCP stream(TCP)  65475 non-null  float64
 18  Time since first frame(UDP)                        25730 non-null  float64
 19  Time since previous frame(UDP)                     25730 non-null  float64
 20  Attack                                             65475 non-null  int64
dtypes: float64(9), int64(8), object(4)
memory usage: 10.5+ MB

In [92]:
svm_model.score(X2,Y2)

0.8191981672394043

In [93]:
adaboost_model.score(X2,Y2)

0.9998167239404353

In [94]:
decision_tree.score(X2,Y2)

0.999663993890798

In [95]:
mlp_model.score(X2,Y2)

0.7952806414662085

In [96]:
#testing with third pcap file

exfiltration_csv3_file= os.path.join(here, 'IOT_data_theft_1233.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df3=pd.read_csv(exfiltration_csv3_file)

In [97]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,Window,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack
0,0.000000,192.168.100.3,50032,TCP,192.168.100.150,4433,13098,0x010,13032.0,13032.0,8666.0,64,0x40,0x00,NaN,0.000000,0.000000,NaN,NaN,1
1,0.000006,192.168.100.3,50032,TCP,192.168.100.150,4433,13098,0x010,26064.0,26064.0,8666.0,64,0x40,0x00,NaN,0.000006,0.000006,NaN,NaN,1
2,0.000012,192.168.100.3,50032,TCP,192.168.100.150,4433,13098,0x018,39096.0,39096.0,8666.0,64,0x40,0x00,NaN,0.000012,0.000006,NaN,NaN,1
3,0.000017,192.168.100.3,50032,TCP,192.168.100.150,4433,13098,0x010,52128.0,13032.0,8666.0,64,0x40,0x00,NaN,0.000017,0.000005,NaN,NaN,1
4,0.000022,192.168.100.3,50032,TCP,192.168.100.150,4433,13098,0x010,65160.0,26064.0,8666.0,64,0x40,0x00,NaN,0.000022,0.000005,NaN,NaN,1

In [98]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53984 entries, 0 to 53983
Data columns (total 20 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   Time                                               53984 non-null  float64
 1   saddr                                              53984 non-null  object
 2   sport                                              53984 non-null  int64
 3   Protocol                                           53984 non-null  object
 4   daddr                                              53984 non-null  object
 5   dport                                              53984 non-null  int64
 6   Length                                             53984 non-null  int64
 7   TCP_Flags                                          36784 non-null  object
 8   Bytes in flight                                    31848 non-null  float64
 9   Bytes sent since last PSH flag                     31848 non-null  float64
 10  Window                                             36784 non-null  float64
 11  Time to Live                                       53984 non-null  int64
 12  IPv4_frag_Flags                                    53984 non-null  object
 13  Differentiated Services Field                      53984 non-null  object
 14  The RTT to ACK the segment was                     4468 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     36784 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  36784 non-null  float64
 17  Time since first frame(UDP)                        17200 non-null  float64
 18  Time since previous frame(UDP)                     17200 non-null  float64
 19  Attack                                             53984 non-null  int64
dtypes: float64(9), int64(5), object(6)
memory usage: 8.2+ MB

In [99]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df3['Protocol']=[protocol_vals[k] for k in df3['Protocol']]

In [101]:
df3['Window']=df3['Window'].fillna(0)
df3['dport']=df3['dport'].fillna(0)
df3['sport']=df3['sport'].fillna(0)
df3['TCP_Flags']=df3['TCP_Flags'].fillna('0x000')
df3['Bytes in flight']=df3['Bytes in flight'].fillna(0)
df3['Bytes sent since last PSH flag']=df3['Bytes sent since last PSH flag'].fillna(0)
df3['The RTT to ACK the segment was']=df3['The RTT to ACK the segment was'].fillna(0)
df3['Time since previous frame in this TCP stream(TCP)']=df3['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [102]:
from ast import literal_eval
df3['TCP_Flags']=[literal_eval(k) for k in df3['TCP_Flags']]

In [103]:
X3=df3[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Bytes sent since last PSH flag','Time since previous frame in this TCP stream(TCP)']].values
Y3=df3['Attack'].values

In [48]:
svm_model.score(X3,Y3)

0.6683461766449318

In [104]:
adaboost_model.score(X3,Y3)

0.9999629519857736

In [105]:
mlp_model.score(X3,Y3)

0.6451170717249556

In [106]:
decision_tree.score(X3,Y3)

0.9987959395376408

In [32]:

import pickle
with open('svm_exfiltration_dec06_n_scaled.pickle', 'wb') as f: 
    pickle.dump(svm_model, f)

In [33]:
import pickle
with open('adaboost_exfiltration_dec06_n_scaled.pickle', 'wb') as f: 
    pickle.dump(adaboost_model, f)

In [35]:
import pickle
with open('mlp_exfiltration_dec06_n_scaled.pickle', 'wb') as f: 
    pickle.dump(mlp_model, f)

In [36]:
import pickle
with open('decision_tree_efiltration_dec06_n_scaled.pickle', 'wb') as f: 
    pickle.dump(decision_tree, f)