In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import os

here = os.path.abspath('') #get the current directory the python file is in, just place all teh other files in this folder

keylogging_csv1_file= os.path.join(here, 'IOT_keylogging_5903_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df=pd.read_csv(keylogging_csv1_file)
#df2=pd.read_csv(exfiltration_csv2_file)
#df3=pd.read_csv(os_scan_csv,sep=";")

In [2]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,1320,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
1,0.000005,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,769,0x000,715.0,715.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
2,0.000006,192.168.100.46,80.0,UDP,192.168.100.5,80.0,953,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
3,0.000010,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,889,0x000,835.0,835.0,...,127.0,0x00,0x00,NaN,0.000005,0.000005,NaN,NaN,0,NaN
4,0.000014,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,693,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000014,0.000014,0,NaN

In [3]:
#df['sport'][df['No.']].hist()

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365133 entries, 0 to 365132
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               365133 non-null  float64
 1   saddr                                              365133 non-null  object
 2   sport                                              365016 non-null  float64
 3   Protocol                                           365133 non-null  object
 4   daddr                                              365133 non-null  object
 5   dport                                              365016 non-null  float64
 6   Length                                             365133 non-null  int64
 7   TCP_Flags                                          218481 non-null  object
 8   Bytes in flight                                    187395 non-null  float64
 9   Bytes sent since last PSH flag                     187395 non-null  float64
 10  Window                                             218481 non-null  float64
 11  Time to Live                                       365024 non-null  float64
 12  IPv4_frag_Flags                                    365024 non-null  object
 13  Differentiated Services Field                      365024 non-null  object
 14  The RTT to ACK the segment was                     30032 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     218481 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  218481 non-null  float64
 17  Time since first frame(UDP)                        146535 non-null  float64
 18  Time since previous frame(UDP)                     146535 non-null  float64
 19  Attack                                             365133 non-null  int64
 20  iRTT                                               5058 non-null    float64
dtypes: float64(13), int64(2), object(6)
memory usage: 58.5+ MB

In [4]:
df['Attack']

0         0
1         0
2         0
3         0
4         0
         ..
365128    0
365129    0
365130    0
365131    0
365132    0
Name: Attack, Length: 365133, dtype: int64

In [5]:
len(df)

365133

In [6]:
df.isnull().values.any()

True

In [7]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df['Protocol']=[protocol_vals[k] for k in df['Protocol']]

In [8]:
df['Protocol']

0         5
1         4
2         5
3         4
4         5
         ..
365128    4
365129    4
365130    4
365131    4
365132    4
Name: Protocol, Length: 365133, dtype: int64

In [9]:
df.head(20)

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,3456.0,5,192.168.100.5,80.0,1320,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
1,0.000005,192.168.100.55,8080.0,4,192.168.100.3,80.0,769,0x000,715.0,715.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
2,0.000006,192.168.100.46,80.0,5,192.168.100.5,80.0,953,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
3,0.000010,192.168.100.3,80.0,4,192.168.100.55,8080.0,889,0x000,835.0,835.0,...,127.0,0x00,0x00,NaN,0.000005,0.000005,NaN,NaN,0,NaN
4,0.000014,192.168.100.5,80.0,5,192.168.100.46,3456.0,693,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000014,0.000014,0,NaN
5,0.000016,192.168.100.46,80.0,4,192.168.100.5,80.0,1023,0x000,969.0,969.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
6,0.000018,192.168.100.5,0.0,4,192.168.100.3,0.0,180,0x000,126.0,126.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
7,0.012438,192.168.100.46,3456.0,5,192.168.100.5,80.0,905,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.012438,0.012424,0,NaN
8,0.012441,192.168.100.55,8080.0,4,192.168.100.3,80.0,917,0x000,863.0,1578.0,...,127.0,0x00,0x00,NaN,0.012436,0.012431,NaN,NaN,0,NaN
9,0.012442,192.168.100.46,80.0,5,192.168.100.5,80.0,1387,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.012436,0.012436,0,NaN
10,0.012445,192.168.100.6,80.0,4,192.168.100.3,80.0,296,0x000,242.0,242.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,1,NaN
11,0.012448,192.168.100.3,80.0,4,192.168.100.55,8080.0,682,0x000,835.0,1463.0,...,127.0,0x00,0x00,NaN,0.012443,0.000007,NaN,NaN,0,NaN
12,0.012452,192.168.100.5,80.0,5,192.168.100.46,3456.0,960,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.012452,0.000014,0,NaN
13,0.012454,192.168.100.46,80.0,4,192.168.100.5,80.0,477,0x000,969.0,1392.0,...,127.0,0x00,0x00,NaN,0.012438,0.012438,NaN,NaN,0,NaN
14,0.012457,192.168.100.5,0.0,4,192.168.100.3,0.0,529,0x000,475.0,601.0,...,127.0,0x00,0x00,NaN,0.012439,0.012439,NaN,NaN,0,NaN
15,0.012458,192.168.100.7,365.0,5,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
16,0.024954,192.168.100.46,3456.0,5,192.168.100.5,80.0,895,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.024954,0.012502,0,NaN
17,0.024960,192.168.100.55,8080.0,4,192.168.100.3,80.0,1260,0x000,1206.0,2784.0,...,127.0,0x00,0x00,NaN,0.024955,0.012512,NaN,NaN,0,NaN
18,0.024964,192.168.100.46,80.0,5,192.168.100.5,80.0,1172,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.024958,0.012522,0,NaN
19,0.024972,192.168.100.3,80.0,4,192.168.100.55,8080.0,921,0x000,867.0,2330.0,...,127.0,0x00,0x00,NaN,0.024967,0.000012,NaN,NaN,0,NaN

In [10]:


df['Window']=df['Window'].fillna(0)
df['dport']=df['dport'].fillna(0)
df['sport']=df['sport'].fillna(0)
df['TCP_Flags']=df['TCP_Flags'].fillna('0x000')
df['Bytes in flight']=df['Bytes in flight'].fillna(0)
#df['Bytes sent since last PSH flag']=df['Bytes sent since last PSH flag'].fillna(0)
df['The RTT to ACK the segment was']=df['The RTT to ACK the segment was'].fillna(0)
df['Time since previous frame in this TCP stream(TCP)']=df['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [11]:
from ast import literal_eval
df['TCP_Flags']=[literal_eval(k) for k in df['TCP_Flags']]
#df.info()

In [12]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,3456.0,5,192.168.100.5,80.0,1320,0,0.0,0.0,...,127.0,0x00,0x00,0.0,NaN,0.000000,0.000000,0.000000,0,NaN
1,0.000005,192.168.100.55,8080.0,4,192.168.100.3,80.0,769,0,715.0,715.0,...,127.0,0x00,0x00,0.0,0.000000,0.000000,NaN,NaN,0,NaN
2,0.000006,192.168.100.46,80.0,5,192.168.100.5,80.0,953,0,0.0,0.0,...,127.0,0x00,0x00,0.0,NaN,0.000000,0.000000,0.000000,0,NaN
3,0.000010,192.168.100.3,80.0,4,192.168.100.55,8080.0,889,0,835.0,835.0,...,127.0,0x00,0x00,0.0,0.000005,0.000005,NaN,NaN,0,NaN
4,0.000014,192.168.100.5,80.0,5,192.168.100.46,3456.0,693,0,0.0,0.0,...,127.0,0x00,0x00,0.0,NaN,0.000000,0.000014,0.000014,0,NaN

In [17]:
#import sklearn
#from sklearn.preprocessing import StandardScaler

In [18]:
#sc=StandardScaler()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381055 entries, 0 to 381054
Data columns (total 12 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   No.         284828 non-null  float64
 1   Time        381055 non-null  float64
 2   saddr       381055 non-null  object
 3   sport       381055 non-null  float64
 4   Protocol    381055 non-null  int64
 5   daddr       381055 non-null  object
 6   dport       381055 non-null  float64
 7   Length      381055 non-null  int64
 8   TCP_Flags   381055 non-null  int64
 9   Window      381055 non-null  float64
 10  UDP Length  131587 non-null  float64
 11  Attack      381055 non-null  int64
dtypes: float64(6), int64(4), object(2)
memory usage: 34.9+ MB

In [15]:
X=df[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)']].values
Y=df['Attack'].values

In [16]:
X.shape

(365133, 8)

In [20]:
import sklearn
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#X=sc.fit_transform(X)

scaler=sc.fit(X)
X=scaler.transform(X)

import pickle
pickle.dump(sc, open('keylogging_scaler_.pkl','wb'))#should i put the scaler instead of sc???

In [25]:
X

array([[-0.16265001, -0.48647472,  1.21911174, ..., -0.4811719 ,
        -0.47716724, -0.03449616],
       [ 0.19703907, -0.48647472, -0.81573008, ..., -0.4811719 ,
        -0.08023828, -0.03449616],
       [-0.42526037, -0.48647472,  1.21911174, ..., -0.4811719 ,
        -0.47716724, -0.03449616],
       ...,
       [ 2.62245115, -0.46233597, -0.81573008, ...,  1.60350488,
        -0.47716724, -0.01705632],
       [-0.39702353,  2.118914  , -0.81573008, ...,  2.64584327,
        -0.39056456, -0.03444898],
       [ 2.62245115, -0.46233597, -0.81573008, ...,  1.60350488,
        -0.47716724, -0.03446602]])

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.25)

In [24]:
X_train

array([[ 0.19703907, -0.48647472, -0.81573008, ..., -0.4811719 ,
         0.32390757, -0.02928039],
       [-0.42526037, -0.48647472, -0.81573008, ..., -0.4811719 ,
         0.33223475, -0.02928417],
       [-0.42526037, -0.26197772,  1.21911174, ..., -0.4811719 ,
        -0.47716724, -0.03449616],
       ...,
       [ 0.19703907, -0.48647472, -0.81573008, ..., -0.4811719 ,
         0.32390757, -0.03448691],
       [-0.42526037, -0.26197772,  1.21911174, ..., -0.4811719 ,
        -0.47716724, -0.03449616],
       [-0.39702353,  3.46044314, -0.81573008, ...,  1.60350488,
         1.95436961, -0.03449609]])

In [26]:
from sklearn import svm
from sklearn.ensemble import AdaBoostClassifier 
from sklearn.neural_network import MLPClassifier
from sklearn import tree

In [27]:
svm_model=svm.SVC()
adaboost_model=AdaBoostClassifier()
mlp_model=MLPClassifier(hidden_layer_sizes=(10,7,4))
decision_tree=tree.DecisionTreeClassifier()

In [28]:
svm_model.fit(X_train,Y_train)

SVC()

In [29]:
adaboost_model.fit(X_train,Y_train)

AdaBoostClassifier()

In [30]:
mlp_model.fit(X_train,Y_train)

MLPClassifier(hidden_layer_sizes=(10, 7, 4))

In [31]:
decision_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [32]:
svm_model.score(X_test,Y_test)

0.9988716533017834

In [33]:
adaboost_model.score(X_test,Y_test)

0.9997918583760571

In [34]:
mlp_model.score(X_test,Y_test)

0.9971955654879278

In [35]:
decision_tree.score(X_test,Y_test)

0.999945225888436

In [48]:
#now to import the second pcap file as test it
keylogging_csv2_file= os.path.join(here, 'IOT_keylogging_0719_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df2=pd.read_csv(keylogging_csv2_file)

In [47]:
df2.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,436,0x000,382.0,382.0,...,127.0,0x00,0x00,NaN,0.0,0.0,NaN,NaN,0,NaN
1,0.000004,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,1501,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
2,0.000006,192.168.100.46,80.0,TCP,192.168.100.5,80.0,730,0x000,676.0,676.0,...,127.0,0x00,0x00,NaN,0.0,0.0,NaN,NaN,0,NaN
3,0.000007,192.168.100.7,365.0,UDP,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.012523,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,1182,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.012519,0.012519,0,NaN

In [38]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df2['Protocol']=[protocol_vals[k] for k in df2['Protocol']]

In [39]:
df2['Window']=df2['Window'].fillna(0)
df2['dport']=df2['dport'].fillna(0)
df2['sport']=df2['sport'].fillna(0)
df2['TCP_Flags']=df2['TCP_Flags'].fillna('0x000')
df2['Bytes in flight']=df2['Bytes in flight'].fillna(0)
#df2['Bytes sent since last PSH flag']=df2['Bytes sent since last PSH flag'].fillna(0)
df2['The RTT to ACK the segment was']=df2['The RTT to ACK the segment was'].fillna(0)
df2['Time since previous frame in this TCP stream(TCP)']=df2['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [40]:
from ast import literal_eval
df2['TCP_Flags']=[literal_eval(k) for k in df2['TCP_Flags']]

In [41]:
X2=df2[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)']].values
Y2=df2['Attack'].values

In [42]:
df2.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,80.0,5,192.168.100.5,80.0,1354,0,0.0,NaN,...,127.0,0x00,0x00,0.0,NaN,0.0,0.000000,0.000000,0,NaN
1,0.000003,192.168.100.5,80.0,5,192.168.100.46,3456.0,436,0,0.0,NaN,...,127.0,0x00,0x00,0.0,NaN,0.0,0.000000,0.000000,0,NaN
2,0.000004,192.168.100.46,80.0,4,192.168.100.5,80.0,992,0,938.0,938.0,...,127.0,0x00,0x00,0.0,0.0,0.0,NaN,NaN,0,NaN
3,0.000006,192.168.100.5,0.0,4,192.168.100.3,0.0,180,0,126.0,126.0,...,127.0,0x00,0x00,0.0,0.0,0.0,NaN,NaN,0,NaN
4,0.010902,192.168.100.46,3456.0,5,192.168.100.5,80.0,1106,0,0.0,NaN,...,127.0,0x00,0x00,0.0,NaN,0.0,0.010899,0.010899,0,NaN

In [43]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365385 entries, 0 to 365384
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               365385 non-null  float64
 1   saddr                                              365385 non-null  object
 2   sport                                              365385 non-null  float64
 3   Protocol                                           365385 non-null  int64
 4   daddr                                              365385 non-null  object
 5   dport                                              365385 non-null  float64
 6   Length                                             365385 non-null  int64
 7   TCP_Flags                                          365385 non-null  int64
 8   Bytes in flight                                    365385 non-null  float64
 9   Bytes sent since last PSH flag                     187602 non-null  float64
 10  Window                                             365385 non-null  float64
 11  Time to Live                                       365255 non-null  float64
 12  IPv4_frag_Flags                                    365255 non-null  object
 13  Differentiated Services Field                      365255 non-null  object
 14  The RTT to ACK the segment was                     365385 non-null  float64
 15  Time since first frame in this TCP stream(TCP)     218124 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  365385 non-null  float64
 17  Time since first frame(UDP)                        147117 non-null  float64
 18  Time since previous frame(UDP)                     147117 non-null  float64
 19  Attack                                             365385 non-null  int64
 20  iRTT                                               3633 non-null    float64
dtypes: float64(13), int64(4), object(4)
memory usage: 58.5+ MB

In [44]:
svm_model.score(X2,Y2)

0.04829426495340531

In [45]:
adaboost_model.score(X2,Y2)

0.9516674192974534

In [49]:
#testing with third pcap file

keylogging_csv3_file= os.path.join(here, 'IOT_keylogging_1524_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df3=pd.read_csv(keylogging_csv3_file)

In [50]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,436,0x000,382.0,382.0,...,127.0,0x00,0x00,NaN,0.0,0.0,NaN,NaN,0,NaN
1,0.000004,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,1501,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
2,0.000006,192.168.100.46,80.0,TCP,192.168.100.5,80.0,730,0x000,676.0,676.0,...,127.0,0x00,0x00,NaN,0.0,0.0,NaN,NaN,0,NaN
3,0.000007,192.168.100.7,365.0,UDP,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.012523,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,1182,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.012519,0.012519,0,NaN

In [51]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146220 entries, 0 to 146219
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               146220 non-null  float64
 1   saddr                                              146220 non-null  object
 2   sport                                              146186 non-null  float64
 3   Protocol                                           146220 non-null  object
 4   daddr                                              146220 non-null  object
 5   dport                                              146186 non-null  float64
 6   Length                                             146220 non-null  int64
 7   TCP_Flags                                          100302 non-null  object
 8   Bytes in flight                                    72942 non-null   float64
 9   Bytes sent since last PSH flag                     72942 non-null   float64
 10  Window                                             100302 non-null  float64
 11  Time to Live                                       146187 non-null  float64
 12  IPv4_frag_Flags                                    146187 non-null  object
 13  Differentiated Services Field                      146187 non-null  object
 14  The RTT to ACK the segment was                     26744 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     100302 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  100302 non-null  float64
 17  Time since first frame(UDP)                        45884 non-null   float64
 18  Time since previous frame(UDP)                     45884 non-null   float64
 19  Attack                                             146220 non-null  int64
 20  iRTT                                               110 non-null     float64
dtypes: float64(13), int64(2), object(6)
memory usage: 23.4+ MB

In [52]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df3['Protocol']=[protocol_vals[k] for k in df3['Protocol']]

In [53]:
df3['Window']=df3['Window'].fillna(0)
df3['dport']=df3['dport'].fillna(0)
df3['sport']=df3['sport'].fillna(0)
df3['TCP_Flags']=df3['TCP_Flags'].fillna('0x000')
df3['Bytes in flight']=df3['Bytes in flight'].fillna(0)
#df3['Bytes sent since last PSH flag']=df3['Bytes sent since last PSH flag'].fillna(0)
df3['The RTT to ACK the segment was']=df3['The RTT to ACK the segment was'].fillna(0)
df3['Time since previous frame in this TCP stream(TCP)']=df3['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [54]:
from ast import literal_eval
df3['TCP_Flags']=[literal_eval(k) for k in df3['TCP_Flags']]

In [55]:
X3=df3[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)']].values
Y3=df3['Attack'].values

In [56]:
svm_model.score(X3,Y3)

0.02260976610586787

In [57]:
adaboost_model.score(X3,Y3)

0.9773833948844207

In [58]:
mlp_model.score(X3,Y3)

0.8150253043359321

In [59]:
decision_tree.score(X3,Y3)

0.9773902338941322

In [60]:

import pickle
with open('svm_keylogging_dec07_scaled.pickle', 'wb') as f: 
    pickle.dump(svm_model, f)

In [61]:
import pickle
with open('adaboost_keylogging_dec07_scaled.pickle', 'wb') as f: 
    pickle.dump(adaboost_model, f)

In [62]:
import pickle
with open('mlp_keylogging_dec07_scaled.pickle', 'wb') as f: 
    pickle.dump(mlp_model, f)

In [63]:
import pickle
with open('decision_tree_keylogging_dec07_scaled.pickle', 'wb') as f: 
    pickle.dump(decision_tree, f)