In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import os

here = os.path.abspath('') #get the current directory the python file is in, just place all teh other files in this folder

osscan_csv1_file= os.path.join(here, 'IOT_os_scan_0502_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df=pd.read_csv(osscan_csv1_file)
#df2=pd.read_csv(exfiltration_csv2_file)
#df3=pd.read_csv(os_scan_csv,sep=";")

In [4]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,80.0,TCP,192.168.100.5,80.0,1160,0x000,1106.0,1106.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000003,192.168.100.46,80.0,UDP,192.168.100.5,80.0,750,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.0,0.0,0,NaN
2,0.000005,192.168.100.5,0.0,TCP,192.168.100.3,0.0,843,0x000,789.0,789.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,1,NaN
3,0.046545,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,783,0x000,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
4,0.046554,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,634,0x000,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000009,0.000009,NaN,NaN,0,NaN

In [3]:
#df['sport'][df['No.']].hist()

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466226 entries, 0 to 466225
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               466226 non-null  float64
 1   saddr                                              466226 non-null  object
 2   sport                                              464946 non-null  float64
 3   Protocol                                           466226 non-null  object
 4   daddr                                              466226 non-null  object
 5   dport                                              464946 non-null  float64
 6   Length                                             466226 non-null  int64
 7   TCP_Flags                                          325646 non-null  object
 8   Bytes in flight                                    181418 non-null  float64
 9   Bytes sent since last PSH flag                     181418 non-null  float64
 10  Window                                             325646 non-null  float64
 11  Time to Live                                       465611 non-null  float64
 12  IPv4_frag_Flags                                    465611 non-null  object
 13  Differentiated Services Field                      465611 non-null  object
 14  The RTT to ACK the segment was                     86767 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     325646 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  325646 non-null  float64
 17  Time since first frame(UDP)                        139300 non-null  float64
 18  Time since previous frame(UDP)                     139300 non-null  float64
 19  Attack                                             466226 non-null  int64
 20  iRTT                                               62659 non-null   float64
dtypes: float64(13), int64(2), object(6)
memory usage: 74.7+ MB

In [6]:
df['Protocol']

0         TCP
1         UDP
2         TCP
3         TCP
4         TCP
         ...
466221    TCP
466222    TCP
466223    TCP
466224    TCP
466225    TCP
Name: Protocol, Length: 466226, dtype: object

In [7]:
len(df)

466226

In [8]:
df.isnull().values.any()

True

In [9]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df['Protocol']=[protocol_vals[k] for k in df['Protocol']]

In [10]:
df['Protocol']

0         4
1         5
2         4
3         4
4         4
         ..
466221    4
466222    4
466223    4
466224    4
466225    4
Name: Protocol, Length: 466226, dtype: int64

In [11]:
df.head(20)

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,80.0,4,192.168.100.5,80.0,1160,0x000,1106.0,1106.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000003,192.168.100.46,80.0,5,192.168.100.5,80.0,750,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
2,0.000005,192.168.100.5,0.0,4,192.168.100.3,0.0,843,0x000,789.0,789.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,1,NaN
3,0.046545,192.168.100.3,80.0,4,192.168.100.55,8080.0,783,0x000,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
4,0.046554,192.168.100.55,8080.0,4,192.168.100.3,80.0,634,0x000,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000009,0.000009,NaN,NaN,0,NaN
5,0.046559,192.168.100.46,3456.0,5,192.168.100.5,80.0,831,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
6,0.046561,192.168.100.5,80.0,5,192.168.100.46,3456.0,469,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000002,0.000002,0,NaN
7,0.049627,192.168.100.7,365.0,5,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,1,NaN
8,0.049635,192.168.100.46,80.0,4,192.168.100.5,80.0,1485,0x000,1431.0,2537.0,...,127.0,0x00,0x00,NaN,0.049635,0.049635,NaN,NaN,0,NaN
9,0.049638,192.168.100.46,80.0,5,192.168.100.5,80.0,1449,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.049635,0.049635,0,NaN
10,0.049640,192.168.100.6,80.0,4,192.168.100.3,80.0,296,0x000,242.0,242.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,1,NaN
11,0.093219,192.168.100.3,80.0,4,192.168.100.55,8080.0,511,0x000,729.0,1186.0,...,127.0,0x00,0x00,NaN,0.046674,0.046665,NaN,NaN,0,NaN
12,0.093227,192.168.100.55,8080.0,4,192.168.100.3,80.0,907,0x000,853.0,1433.0,...,127.0,0x00,0x00,NaN,0.046682,0.000008,NaN,NaN,0,NaN
13,0.093240,192.168.100.46,3456.0,5,192.168.100.5,80.0,680,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.046681,0.046679,0,NaN
14,0.093244,192.168.100.5,80.0,5,192.168.100.46,3456.0,955,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.046685,0.000004,0,NaN
15,0.093247,192.168.100.46,80.0,4,192.168.100.5,80.0,635,0x000,1431.0,3118.0,...,127.0,0x00,0x00,NaN,0.093247,0.043612,NaN,NaN,0,NaN
16,0.093249,192.168.100.46,80.0,5,192.168.100.5,80.0,1445,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.093246,0.043611,0,NaN
17,0.093264,192.168.100.5,0.0,4,192.168.100.3,0.0,1297,0x000,1243.0,2032.0,...,127.0,0x00,0x00,NaN,0.093259,0.093259,NaN,NaN,1,NaN
18,0.139768,192.168.100.3,80.0,4,192.168.100.55,8080.0,1444,0x000,1390.0,2576.0,...,127.0,0x00,0x00,NaN,0.093223,0.046541,NaN,NaN,0,NaN
19,0.139790,192.168.100.46,3456.0,5,192.168.100.5,80.0,807,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.093231,0.046546,0,NaN

In [14]:


df['Window']=df['Window'].fillna(0)
df['dport']=df['dport'].fillna(0)
df['sport']=df['sport'].fillna(0)
df['TCP_Flags']=df['TCP_Flags'].fillna('0x000')
df['Time to Live']=df['Time to Live'].fillna(0)
df['Bytes in flight']=df['Bytes in flight'].fillna(0)
df['Time since previous frame(UDP)']=df['Time since previous frame(UDP)'].fillna(0)
df['Time since previous frame in this TCP stream(TCP)']=df['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466226 entries, 0 to 466225
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               466226 non-null  float64
 1   saddr                                              466226 non-null  object
 2   sport                                              466226 non-null  float64
 3   Protocol                                           466226 non-null  int64
 4   daddr                                              466226 non-null  object
 5   dport                                              466226 non-null  float64
 6   Length                                             466226 non-null  int64
 7   TCP_Flags                                          466226 non-null  object
 8   Bytes in flight                                    466226 non-null  float64
 9   Bytes sent since last PSH flag                     181418 non-null  float64
 10  Window                                             466226 non-null  float64
 11  Time to Live                                       466226 non-null  float64
 12  IPv4_frag_Flags                                    465611 non-null  object
 13  Differentiated Services Field                      465611 non-null  object
 14  The RTT to ACK the segment was                     86767 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     325646 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  466226 non-null  float64
 17  Time since first frame(UDP)                        139300 non-null  float64
 18  Time since previous frame(UDP)                     466226 non-null  float64
 19  Attack                                             466226 non-null  int64
 20  iRTT                                               62659 non-null   float64
dtypes: float64(13), int64(3), object(5)
memory usage: 74.7+ MB

In [16]:
from ast import literal_eval
df['TCP_Flags']=[literal_eval(k) for k in df['TCP_Flags']]

In [17]:
df.head(20)

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,80.0,4,192.168.100.5,80.0,1160,0,1106.0,1106.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
1,0.000003,192.168.100.46,80.0,5,192.168.100.5,80.0,750,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
2,0.000005,192.168.100.5,0.0,4,192.168.100.3,0.0,843,0,789.0,789.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,1,NaN
3,0.046545,192.168.100.3,80.0,4,192.168.100.55,8080.0,783,0,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
4,0.046554,192.168.100.55,8080.0,4,192.168.100.3,80.0,634,0,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000009,0.000009,NaN,0.000000,0,NaN
5,0.046559,192.168.100.46,3456.0,5,192.168.100.5,80.0,831,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
6,0.046561,192.168.100.5,80.0,5,192.168.100.46,3456.0,469,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000002,0.000002,0,NaN
7,0.049627,192.168.100.7,365.0,5,192.168.100.3,565.0,60,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,1,NaN
8,0.049635,192.168.100.46,80.0,4,192.168.100.5,80.0,1485,0,1431.0,2537.0,...,127.0,0x00,0x00,NaN,0.049635,0.049635,NaN,0.000000,0,NaN
9,0.049638,192.168.100.46,80.0,5,192.168.100.5,80.0,1449,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.049635,0.049635,0,NaN
10,0.049640,192.168.100.6,80.0,4,192.168.100.3,80.0,296,0,242.0,242.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,1,NaN
11,0.093219,192.168.100.3,80.0,4,192.168.100.55,8080.0,511,0,729.0,1186.0,...,127.0,0x00,0x00,NaN,0.046674,0.046665,NaN,0.000000,0,NaN
12,0.093227,192.168.100.55,8080.0,4,192.168.100.3,80.0,907,0,853.0,1433.0,...,127.0,0x00,0x00,NaN,0.046682,0.000008,NaN,0.000000,0,NaN
13,0.093240,192.168.100.46,3456.0,5,192.168.100.5,80.0,680,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.046681,0.046679,0,NaN
14,0.093244,192.168.100.5,80.0,5,192.168.100.46,3456.0,955,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.046685,0.000004,0,NaN
15,0.093247,192.168.100.46,80.0,4,192.168.100.5,80.0,635,0,1431.0,3118.0,...,127.0,0x00,0x00,NaN,0.093247,0.043612,NaN,0.000000,0,NaN
16,0.093249,192.168.100.46,80.0,5,192.168.100.5,80.0,1445,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.093246,0.043611,0,NaN
17,0.093264,192.168.100.5,0.0,4,192.168.100.3,0.0,1297,0,1243.0,2032.0,...,127.0,0x00,0x00,NaN,0.093259,0.093259,NaN,0.000000,1,NaN
18,0.139768,192.168.100.3,80.0,4,192.168.100.55,8080.0,1444,0,1390.0,2576.0,...,127.0,0x00,0x00,NaN,0.093223,0.046541,NaN,0.000000,0,NaN
19,0.139790,192.168.100.46,3456.0,5,192.168.100.5,80.0,807,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.093231,0.046546,0,NaN

In [18]:
#from ast import literal_eval
#df2['TCP Flag']=[literal_eval(k) for k in df2['TCP Flag']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466226 entries, 0 to 466225
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               466226 non-null  float64
 1   saddr                                              466226 non-null  object
 2   sport                                              466226 non-null  float64
 3   Protocol                                           466226 non-null  int64
 4   daddr                                              466226 non-null  object
 5   dport                                              466226 non-null  float64
 6   Length                                             466226 non-null  int64
 7   TCP_Flags                                          466226 non-null  int64
 8   Bytes in flight                                    466226 non-null  float64
 9   Bytes sent since last PSH flag                     181418 non-null  float64
 10  Window                                             466226 non-null  float64
 11  Time to Live                                       466226 non-null  float64
 12  IPv4_frag_Flags                                    465611 non-null  object
 13  Differentiated Services Field                      465611 non-null  object
 14  The RTT to ACK the segment was                     86767 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     325646 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  466226 non-null  float64
 17  Time since first frame(UDP)                        139300 non-null  float64
 18  Time since previous frame(UDP)                     466226 non-null  float64
 19  Attack                                             466226 non-null  int64
 20  iRTT                                               62659 non-null   float64
dtypes: float64(13), int64(4), object(4)
memory usage: 74.7+ MB

In [15]:
#import sklearn
#from sklearn.preprocessing import StandardScaler

In [19]:
#sc=StandardScaler()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 466226 entries, 0 to 466225
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               466226 non-null  float64
 1   saddr                                              466226 non-null  object
 2   sport                                              466226 non-null  float64
 3   Protocol                                           466226 non-null  int64
 4   daddr                                              466226 non-null  object
 5   dport                                              466226 non-null  float64
 6   Length                                             466226 non-null  int64
 7   TCP_Flags                                          466226 non-null  int64
 8   Bytes in flight                                    466226 non-null  float64
 9   Bytes sent since last PSH flag                     181418 non-null  float64
 10  Window                                             466226 non-null  float64
 11  Time to Live                                       466226 non-null  float64
 12  IPv4_frag_Flags                                    465611 non-null  object
 13  Differentiated Services Field                      465611 non-null  object
 14  The RTT to ACK the segment was                     86767 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     325646 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  466226 non-null  float64
 17  Time since first frame(UDP)                        139300 non-null  float64
 18  Time since previous frame(UDP)                     466226 non-null  float64
 19  Attack                                             466226 non-null  int64
 20  iRTT                                               62659 non-null   float64
dtypes: float64(13), int64(4), object(4)
memory usage: 74.7+ MB

In [20]:
X=df[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)','Time since previous frame(UDP)']].values
Y=df['Attack'].values

In [21]:
X.shape

(466226, 9)

In [23]:
import sklearn
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#X=sc.fit_transform(X)

scaler=sc.fit(X)
X=scaler.transform(X)

import pickle
pickle.dump(sc, open('os_scan_scaler_.pkl','wb'))#should i put the scaler instead of sc???

In [24]:
X

array([[-0.60937672, -0.64788491, -0.59834509, ...,  0.3824705 ,
        -0.02689761, -0.0119027 ],
       [-0.60937672, -0.64788491,  1.45225796, ..., -0.48145361,
        -0.02689761, -0.0119027 ],
       [-0.61350386, -0.6519043 , -0.59834509, ...,  0.13485391,
        -0.02689761, -0.0119027 ],
       ...,
       [ 1.41189195, -0.62964689, -0.59834509, ..., -0.48145361,
        -0.01992673, -0.0119027 ],
       [-0.59064981,  1.32061508, -0.59834509, ..., -0.35959813,
        -0.02687875, -0.0119027 ],
       [ 1.41189195, -0.62964689, -0.59834509, ..., -0.48145361,
        -0.02688556, -0.0119027 ]])

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X_train,X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.25)

In [27]:
X_train

array([[ 2.24965056, -0.4574157 , -0.59834509, ..., -0.48145361,
        -0.02689761, -0.0119027 ],
       [-0.59064981,  2.10067968, -0.59834509, ...,  0.56525372,
        -0.02688725, -0.0119027 ],
       [-0.60937672, -0.64788491, -0.59834509, ..., -0.29242139,
        -0.00359339, -0.0119027 ],
       ...,
       [-0.43521125, -0.64788491,  1.45225796, ..., -0.48145361,
        -0.02689761, -0.00258434],
       [-0.41921857,  1.59242685, -0.59834509, ..., -0.48145361,
        -0.02688769, -0.0119027 ],
       [-0.56227569,  2.0731468 , -0.59834509, ..., -0.48145361,
        -0.02688365, -0.0119027 ]])

In [28]:
from sklearn import svm
from sklearn.ensemble import AdaBoostClassifier 
from sklearn import tree
from sklearn.neural_network import MLPClassifier

In [29]:
svm_model=svm.SVC()
adaboost_model=AdaBoostClassifier()
decision_tree=tree.DecisionTreeClassifier()
mlp_model=MLPClassifier(hidden_layer_sizes=(10,7,4))

In [30]:
svm_model.fit(X_train,Y_train)

SVC()

In [31]:
adaboost_model.fit(X_train,Y_train)

AdaBoostClassifier()

In [32]:
decision_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [33]:
#mlp_model=MLPClassifier(hidden_layer_sizes=(10,7,4))
mlp_model.fit(X_train,Y_train)

MLPClassifier(hidden_layer_sizes=(10, 7, 4))

In [34]:
svm_model.score(X_test,Y_test)

0.9955129250066491

In [35]:
adaboost_model.score(X_test,Y_test)

0.9986787580325506

In [36]:
decision_tree.score(X_test,Y_test)

0.9999914205067049

In [37]:
mlp_model.score(X_test,Y_test)

0.9989018248582239

In [52]:
#now to import the second pcap file as test it
osscan_csv2_file= os.path.join(here, 'IOT_os_scan_3228_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df2=pd.read_csv(osscan_csv2_file)

In [53]:
df2.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,947,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
1,0.000001,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,824,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000001,0.000001,0,NaN
2,0.000002,192.168.100.46,80.0,TCP,192.168.100.5,80.0,1130,0x000,1076.0,1076.0,...,127.0,0x00,0x00,NaN,0.0,0.0,NaN,NaN,0,NaN
3,0.000003,192.168.100.46,80.0,UDP,192.168.100.5,80.0,966,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.014822,192.168.100.7,55393.0,UDP,192.168.159.152,53.0,88,NaN,NaN,NaN,...,64.0,0x40,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN

In [54]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df2['Protocol']=[protocol_vals[k] for k in df2['Protocol']]

In [55]:
df2['Window']=df2['Window'].fillna(0)
df2['dport']=df2['dport'].fillna(0)
df2['sport']=df2['sport'].fillna(0)
df2['TCP_Flags']=df2['TCP_Flags'].fillna('0x000')
df2['Time to Live']=df2['Time to Live'].fillna(0)
df2['Bytes in flight']=df2['Bytes in flight'].fillna(0)
df2['Time since previous frame(UDP)']=df2['Time since previous frame(UDP)'].fillna(0)
df2['Time since previous frame in this TCP stream(TCP)']=df2['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [56]:
from ast import literal_eval
df2['TCP_Flags']=[literal_eval(k) for k in df2['TCP_Flags']]

In [57]:
X2=df2[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)','Time since previous frame(UDP)']].values
Y2=df2['Attack'].values

In [64]:
import sklearn
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#X=sc.fit_transform(X)

#scaler=sc.fit(X2)
X2=scaler.transform(X2)

#import pickle
#pickle.dump(sc, open('os_scan_scaler_.pkl','wb'))#should i put the scaler instead of sc???

In [58]:
df2.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.46,3456.0,5,192.168.100.5,80.0,947,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.0,0.000000,0.000000,0,NaN
1,0.000001,192.168.100.5,80.0,5,192.168.100.46,3456.0,824,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.0,0.000001,0.000001,0,NaN
2,0.000002,192.168.100.46,80.0,4,192.168.100.5,80.0,1130,0,1076.0,1076.0,...,127.0,0x00,0x00,NaN,0.0,0.0,NaN,0.000000,0,NaN
3,0.000003,192.168.100.46,80.0,5,192.168.100.5,80.0,966,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.0,0.000000,0.000000,0,NaN
4,0.014822,192.168.100.7,55393.0,5,192.168.159.152,53.0,88,0,0.0,NaN,...,64.0,0x40,0x00,NaN,NaN,0.0,0.000000,0.000000,0,NaN

In [67]:
X2

array([[-0.43521125, -0.64788491,  1.45225796, ..., -0.48145361,
        -0.02689761, -0.0119027 ],
       [-0.60937672, -0.47826633,  1.45225796, ..., -0.48145361,
        -0.02689761, -0.0119025 ],
       [-0.60937672, -0.64788491, -0.59834509, ...,  0.35903675,
        -0.02689761, -0.0119027 ],
       ...,
       [ 1.41189195, -0.62964689, -0.59834509, ..., -0.48145361,
        -0.01992673, -0.0119027 ],
       [-0.59064981,  1.32061508, -0.59834509, ..., -0.35959813,
        -0.02687875, -0.0119027 ],
       [ 1.41189195, -0.62964689, -0.59834509, ..., -0.48145361,
        -0.02688556, -0.0119027 ]])

In [68]:
svm_model.score(X2,Y2)

0.996191440800838

In [70]:
adaboost_model.score(X2,Y2)

0.9987258554227455

In [71]:
decision_tree.score(X2,Y2)

0.9998427552971809

In [72]:
mlp_model.score(X2,Y2)

0.9987605417542497

In [47]:
#testing with third pcap file

osscan_csv3_file= os.path.join(here, 'IOT_OSScan_0020_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df3=pd.read_csv(osscan_csv3_file)

In [48]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Window,Packet Length,Time to Live,IPv4_frag_Flags,Differentiated Services Field,TCP Options,Attack
0,0.000000,192.168.100.5,0.0,TCP,192.168.100.3,0.0,837,0x000,1024.0,NaN,127.0,0x00,0x00,NaN,1
1,0.046600,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,1389,0x000,1024.0,NaN,127.0,0x00,0x00,NaN,0
2,0.046611,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,753,0x000,1024.0,NaN,127.0,0x00,0x00,NaN,0
3,0.046617,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,1419,NaN,NaN,NaN,127.0,0x00,0x00,NaN,0
4,0.046621,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,510,NaN,NaN,NaN,127.0,0x00,0x00,NaN,0

In [49]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131768 entries, 0 to 131767
Data columns (total 15 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Time                           131768 non-null  float64
 1   saddr                          131768 non-null  object
 2   sport                          131627 non-null  float64
 3   Protocol                       131768 non-null  object
 4   daddr                          131768 non-null  object
 5   dport                          131627 non-null  float64
 6   Length                         131768 non-null  int64
 7   TCP_Flags                      38675 non-null   object
 8   Window                         38675 non-null   float64
 9   Packet Length                  0 non-null       float64
 10  Time to Live                   131627 non-null  float64
 11  IPv4_frag_Flags                131627 non-null  object
 12  Differentiated Services Field  131627 non-null  object
 13  TCP Options                    577 non-null     object
 14  Attack                         131768 non-null  int64
dtypes: float64(6), int64(2), object(7)
memory usage: 15.1+ MB

In [50]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df3['Protocol']=[protocol_vals[k] for k in df3['Protocol']]

In [51]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Window,Packet Length,Time to Live,IPv4_frag_Flags,Differentiated Services Field,TCP Options,Attack
0,0.000000,192.168.100.5,0.0,4,192.168.100.3,0.0,837,0x000,1024.0,NaN,127.0,0x00,0x00,NaN,1
1,0.046600,192.168.100.3,80.0,4,192.168.100.55,8080.0,1389,0x000,1024.0,NaN,127.0,0x00,0x00,NaN,0
2,0.046611,192.168.100.55,8080.0,4,192.168.100.3,80.0,753,0x000,1024.0,NaN,127.0,0x00,0x00,NaN,0
3,0.046617,192.168.100.46,3456.0,5,192.168.100.5,80.0,1419,NaN,NaN,NaN,127.0,0x00,0x00,NaN,0
4,0.046621,192.168.100.5,80.0,5,192.168.100.46,3456.0,510,NaN,NaN,NaN,127.0,0x00,0x00,NaN,0

In [52]:
df3['Window']=df3['Window'].fillna(0)
df3['dport']=df3['dport'].fillna(0)
df3['sport']=df3['sport'].fillna(0)
df3['TCP_Flags']=df3['TCP_Flags'].fillna('0x000')
df3['Time to Live']=df3['Time to Live'].fillna(0)

In [53]:
from ast import literal_eval
df3['TCP_Flags']=[literal_eval(k) for k in df3['TCP_Flags']]

In [54]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Window,Packet Length,Time to Live,IPv4_frag_Flags,Differentiated Services Field,TCP Options,Attack
0,0.000000,192.168.100.5,0.0,4,192.168.100.3,0.0,837,0,1024.0,NaN,127.0,0x00,0x00,NaN,1
1,0.046600,192.168.100.3,80.0,4,192.168.100.55,8080.0,1389,0,1024.0,NaN,127.0,0x00,0x00,NaN,0
2,0.046611,192.168.100.55,8080.0,4,192.168.100.3,80.0,753,0,1024.0,NaN,127.0,0x00,0x00,NaN,0
3,0.046617,192.168.100.46,3456.0,5,192.168.100.5,80.0,1419,0,0.0,NaN,127.0,0x00,0x00,NaN,0
4,0.046621,192.168.100.5,80.0,5,192.168.100.46,3456.0,510,0,0.0,NaN,127.0,0x00,0x00,NaN,0

In [55]:
X3=df[['sport','dport','Protocol','Length','TCP_Flags','Time to Live']].values
Y3=df['Attack'].values

In [56]:
svm_model.score(X3,Y3)

0.9175626571094353

In [57]:
adaboost_model.score(X3,Y3)

0.9993653401030389

In [58]:
decision_tree.score(X3,Y3)

0.9999958518960983

In [59]:
mlp_model.score(X3,Y3)

0.994997386694542

In [73]:

import pickle
with open('svm_OSSCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(svm_model, f)

In [74]:
import pickle
with open('adaboost_OSSCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(adaboost_model, f)

In [75]:
import pickle
with open('decission_tree_OSSCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(decision_tree, f)

In [76]:
import pickle
with open('mlp_OSSCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(mlp_model, f)