In [22]:
import pandas as pd
import matplotlib.pyplot as plt
import os

here = os.path.abspath('') #get the current directory the python file is in, just place all teh other files in this folder

service_scan_csv1_file= os.path.join(here, 'IOT_service_scan_2711_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df=pd.read_csv(service_scan_csv1_file)
#df2=pd.read_csv(exfiltration_csv2_file)
#df3=pd.read_csv(os_scan_csv,sep=";")

In [23]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,783,0x000,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000012,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,831,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
2,0.000015,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,469,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000003,0.000003,0,NaN
3,0.000016,192.168.100.46,80.0,UDP,192.168.100.5,80.0,1449,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,634,0x000,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000022,0.000022,NaN,NaN,0,NaN

In [3]:
#df['sport'][df['No.']].hist()

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462512 entries, 0 to 462511
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               462512 non-null  float64
 1   saddr                                              462512 non-null  object
 2   sport                                              457565 non-null  float64
 3   Protocol                                           462512 non-null  object
 4   daddr                                              462512 non-null  object
 5   dport                                              457565 non-null  float64
 6   Length                                             462512 non-null  int64
 7   TCP_Flags                                          319829 non-null  object
 8   Bytes in flight                                    197548 non-null  float64
 9   Bytes sent since last PSH flag                     197548 non-null  float64
 10  Window                                             319829 non-null  float64
 11  Time to Live                                       461916 non-null  float64
 12  IPv4_frag_Flags                                    461916 non-null  object
 13  Differentiated Services Field                      461916 non-null  object
 14  The RTT to ACK the segment was                     91674 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     319829 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  319829 non-null  float64
 17  Time since first frame(UDP)                        132068 non-null  float64
 18  Time since previous frame(UDP)                     132068 non-null  float64
 19  Attack                                             462512 non-null  int64
 20  iRTT                                               89590 non-null   float64
dtypes: float64(13), int64(2), object(6)
memory usage: 74.1+ MB

In [25]:
df['Protocol']

0         TCP
1         UDP
2         UDP
3         UDP
4         TCP
         ...
462507    TCP
462508    TCP
462509    TCP
462510    TCP
462511    TCP
Name: Protocol, Length: 462512, dtype: object

In [26]:
len(df)

462512

In [27]:
df.isnull().values.any()

True

In [28]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0, '0x86dd':6}
df['Protocol']=[protocol_vals[k] for k in df['Protocol']]

In [29]:
df['Protocol']

0         4
1         5
2         5
3         5
4         4
         ..
462507    4
462508    4
462509    4
462510    4
462511    4
Name: Protocol, Length: 462512, dtype: int64

In [30]:
df.head(20)

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,783,0x000,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000012,192.168.100.46,3456.0,5,192.168.100.5,80.0,831,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
2,0.000015,192.168.100.5,80.0,5,192.168.100.46,3456.0,469,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000003,0.000003,0,NaN
3,0.000016,192.168.100.46,80.0,5,192.168.100.5,80.0,1449,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.55,8080.0,4,192.168.100.3,80.0,634,0x000,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000022,0.000022,NaN,NaN,0,NaN
5,0.000024,192.168.100.46,80.0,4,192.168.100.5,80.0,1485,0x000,1431.0,1431.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
6,0.000026,192.168.100.6,80.0,4,192.168.100.3,80.0,296,0x000,242.0,242.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,1,NaN
7,0.000027,192.168.100.7,365.0,5,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,1,NaN
8,0.057784,192.168.100.3,80.0,4,192.168.100.55,8080.0,511,0x000,729.0,1186.0,...,127.0,0x00,0x00,NaN,0.057784,0.057762,NaN,NaN,0,NaN
9,0.057793,192.168.100.46,3456.0,5,192.168.100.5,80.0,680,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.057781,0.057778,0,NaN
10,0.057795,192.168.100.5,80.0,5,192.168.100.46,3456.0,955,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.057783,0.000002,0,NaN
11,0.057800,192.168.100.46,80.0,5,192.168.100.5,80.0,1445,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.057784,0.057784,0,NaN
12,0.057817,192.168.100.55,8080.0,4,192.168.100.3,80.0,907,0x000,853.0,1433.0,...,127.0,0x00,0x00,NaN,0.057817,0.000033,NaN,NaN,0,NaN
13,0.057820,192.168.100.46,80.0,4,192.168.100.5,80.0,635,0x000,1431.0,2012.0,...,127.0,0x00,0x00,NaN,0.057796,0.057796,NaN,NaN,0,NaN
14,0.057822,192.168.100.5,0.0,4,192.168.100.3,0.0,1297,0x000,1243.0,1243.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,1,NaN
15,0.115632,192.168.100.3,80.0,4,192.168.100.55,8080.0,1444,0x000,1390.0,2576.0,...,127.0,0x00,0x00,NaN,0.115632,0.057815,NaN,NaN,0,NaN
16,0.115645,192.168.100.46,3456.0,5,192.168.100.5,80.0,807,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.115633,0.057850,0,NaN
17,0.115647,192.168.100.5,80.0,5,192.168.100.46,3456.0,1327,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.115635,0.000002,0,NaN
18,0.115649,192.168.100.46,80.0,5,192.168.100.5,80.0,707,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.115633,0.057849,0,NaN
19,0.115655,192.168.100.55,8080.0,4,192.168.100.3,80.0,955,0x000,901.0,2334.0,...,127.0,0x00,0x00,NaN,0.115655,0.000023,NaN,NaN,0,NaN

In [31]:


df['Window']=df['Window'].fillna(0)
df['dport']=df['dport'].fillna(0)
df['sport']=df['sport'].fillna(0)
df['TCP_Flags']=df['TCP_Flags'].fillna('0x000')
df['Time to Live']=df['Time to Live'].fillna(0)
df['Bytes in flight']=df['Bytes in flight'].fillna(0)
df['Time since previous frame(UDP)']=df['Time since previous frame(UDP)'].fillna(0)
df['Time since previous frame in this TCP stream(TCP)']=df['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [32]:
df.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,783,0x000,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
1,0.000012,192.168.100.46,3456.0,5,192.168.100.5,80.0,831,0x000,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
2,0.000015,192.168.100.5,80.0,5,192.168.100.46,3456.0,469,0x000,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000003,0.000003,0,NaN
3,0.000016,192.168.100.46,80.0,5,192.168.100.5,80.0,1449,0x000,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.55,8080.0,4,192.168.100.3,80.0,634,0x000,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000022,0.000022,NaN,0.000000,0,NaN

In [33]:
from ast import literal_eval
df['TCP_Flags']=[literal_eval(k) for k in df['TCP_Flags']]

In [34]:
df.head(20)

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,783,0,729.0,729.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
1,0.000012,192.168.100.46,3456.0,5,192.168.100.5,80.0,831,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
2,0.000015,192.168.100.5,80.0,5,192.168.100.46,3456.0,469,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000003,0.000003,0,NaN
3,0.000016,192.168.100.46,80.0,5,192.168.100.5,80.0,1449,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.55,8080.0,4,192.168.100.3,80.0,634,0,580.0,580.0,...,127.0,0x00,0x00,NaN,0.000022,0.000022,NaN,0.000000,0,NaN
5,0.000024,192.168.100.46,80.0,4,192.168.100.5,80.0,1485,0,1431.0,1431.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
6,0.000026,192.168.100.6,80.0,4,192.168.100.3,80.0,296,0,242.0,242.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,1,NaN
7,0.000027,192.168.100.7,365.0,5,192.168.100.3,565.0,60,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,1,NaN
8,0.057784,192.168.100.3,80.0,4,192.168.100.55,8080.0,511,0,729.0,1186.0,...,127.0,0x00,0x00,NaN,0.057784,0.057762,NaN,0.000000,0,NaN
9,0.057793,192.168.100.46,3456.0,5,192.168.100.5,80.0,680,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.057781,0.057778,0,NaN
10,0.057795,192.168.100.5,80.0,5,192.168.100.46,3456.0,955,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.057783,0.000002,0,NaN
11,0.057800,192.168.100.46,80.0,5,192.168.100.5,80.0,1445,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.057784,0.057784,0,NaN
12,0.057817,192.168.100.55,8080.0,4,192.168.100.3,80.0,907,0,853.0,1433.0,...,127.0,0x00,0x00,NaN,0.057817,0.000033,NaN,0.000000,0,NaN
13,0.057820,192.168.100.46,80.0,4,192.168.100.5,80.0,635,0,1431.0,2012.0,...,127.0,0x00,0x00,NaN,0.057796,0.057796,NaN,0.000000,0,NaN
14,0.057822,192.168.100.5,0.0,4,192.168.100.3,0.0,1297,0,1243.0,1243.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,1,NaN
15,0.115632,192.168.100.3,80.0,4,192.168.100.55,8080.0,1444,0,1390.0,2576.0,...,127.0,0x00,0x00,NaN,0.115632,0.057815,NaN,0.000000,0,NaN
16,0.115645,192.168.100.46,3456.0,5,192.168.100.5,80.0,807,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.115633,0.057850,0,NaN
17,0.115647,192.168.100.5,80.0,5,192.168.100.46,3456.0,1327,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.115635,0.000002,0,NaN
18,0.115649,192.168.100.46,80.0,5,192.168.100.5,80.0,707,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.115633,0.057849,0,NaN
19,0.115655,192.168.100.55,8080.0,4,192.168.100.3,80.0,955,0,901.0,2334.0,...,127.0,0x00,0x00,NaN,0.115655,0.000023,NaN,0.000000,0,NaN

In [35]:
#from ast import literal_eval
#df2['TCP Flag']=[literal_eval(k) for k in df2['TCP Flag']]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462512 entries, 0 to 462511
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               462512 non-null  float64
 1   saddr                                              462512 non-null  object
 2   sport                                              462512 non-null  float64
 3   Protocol                                           462512 non-null  int64
 4   daddr                                              462512 non-null  object
 5   dport                                              462512 non-null  float64
 6   Length                                             462512 non-null  int64
 7   TCP_Flags                                          462512 non-null  int64
 8   Bytes in flight                                    462512 non-null  float64
 9   Bytes sent since last PSH flag                     197548 non-null  float64
 10  Window                                             462512 non-null  float64
 11  Time to Live                                       462512 non-null  float64
 12  IPv4_frag_Flags                                    461916 non-null  object
 13  Differentiated Services Field                      461916 non-null  object
 14  The RTT to ACK the segment was                     91674 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     319829 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  462512 non-null  float64
 17  Time since first frame(UDP)                        132068 non-null  float64
 18  Time since previous frame(UDP)                     462512 non-null  float64
 19  Attack                                             462512 non-null  int64
 20  iRTT                                               89590 non-null   float64
dtypes: float64(13), int64(4), object(4)
memory usage: 74.1+ MB

In [16]:
#import sklearn
#from sklearn.preprocessing import StandardScaler

In [36]:
#sc=StandardScaler()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 462512 entries, 0 to 462511
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               462512 non-null  float64
 1   saddr                                              462512 non-null  object
 2   sport                                              462512 non-null  float64
 3   Protocol                                           462512 non-null  int64
 4   daddr                                              462512 non-null  object
 5   dport                                              462512 non-null  float64
 6   Length                                             462512 non-null  int64
 7   TCP_Flags                                          462512 non-null  int64
 8   Bytes in flight                                    462512 non-null  float64
 9   Bytes sent since last PSH flag                     197548 non-null  float64
 10  Window                                             462512 non-null  float64
 11  Time to Live                                       462512 non-null  float64
 12  IPv4_frag_Flags                                    461916 non-null  object
 13  Differentiated Services Field                      461916 non-null  object
 14  The RTT to ACK the segment was                     91674 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     319829 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  462512 non-null  float64
 17  Time since first frame(UDP)                        132068 non-null  float64
 18  Time since previous frame(UDP)                     462512 non-null  float64
 19  Attack                                             462512 non-null  int64
 20  iRTT                                               89590 non-null   float64
dtypes: float64(13), int64(4), object(4)
memory usage: 74.1+ MB

In [37]:
X=df[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)','Time since previous frame(UDP)']].values
Y=df['Attack'].values

In [38]:
X.shape

(462512, 9)

In [21]:
#X=sc.fit_transform(X)

In [39]:
X

array([[8.0000000e+01, 8.0800000e+03, 4.0000000e+00, ..., 7.2900000e+02,
        0.0000000e+00, 0.0000000e+00],
       [3.4560000e+03, 8.0000000e+01, 5.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00],
       [8.0000000e+01, 3.4560000e+03, 5.0000000e+00, ..., 0.0000000e+00,
        0.0000000e+00, 3.0000000e-06],
       ...,
       [3.9260000e+04, 4.4300000e+02, 4.0000000e+00, ..., 0.0000000e+00,
        4.1454854e-02, 0.0000000e+00],
       [4.4300000e+02, 3.9260000e+04, 4.0000000e+00, ..., 1.5600000e+02,
        1.1215100e-04, 0.0000000e+00],
       [3.9260000e+04, 4.4300000e+02, 4.0000000e+00, ..., 0.0000000e+00,
        7.1644000e-05, 0.0000000e+00]])

In [40]:
import sklearn
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

#X=sc.fit_transform(X)

scaler=sc.fit(X)
X=scaler.transform(X)

import pickle
pickle.dump(sc, open('service_scan_scaler_.pkl','wb'))#should i put the scaler instead of sc???

In [41]:
X

array([[-0.6089108 , -0.20561562, -0.4186281 , ...,  0.08061211,
        -0.03442401, -0.00816702],
       [-0.42859045, -0.62712712,  1.19802872, ..., -0.47590796,
        -0.03442401, -0.00816702],
       [-0.6089108 , -0.44924927,  1.19802872, ..., -0.47590796,
        -0.03442401, -0.0081662 ],
       ...,
       [ 1.48378795, -0.60800104, -0.4186281 , ..., -0.47590796,
        -0.01892712, -0.00816702],
       [-0.58952209,  1.43722546, -0.4186281 , ..., -0.35681725,
        -0.03438208, -0.00816702],
       [ 1.48378795, -0.60800104, -0.4186281 , ..., -0.47590796,
        -0.03439722, -0.00816702]])

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train,X_test, Y_train, Y_test= train_test_split(X,Y,test_size=0.25)

In [44]:
X_train

array([[-0.6089108 , -0.62712712, -0.4186281 , ...,  0.61652033,
        -0.01450808, -0.00816702],
       [-0.42859045, -0.62712712,  1.19802872, ..., -0.47590796,
        -0.03442401,  0.00644714],
       [-0.6089108 , -0.62712712, -0.4186281 , ...,  0.61652033,
        -0.01447593, -0.00816702],
       ...,
       [-0.42859045, -0.62712712,  1.19802872, ..., -0.47590796,
        -0.03442401,  0.00646526],
       [-0.42859045, -0.62712712,  1.19802872, ..., -0.47590796,
        -0.03442401,  0.00644988],
       [-0.18161141, -0.62712712, -0.4186281 , ...,  0.56537239,
        -0.03441653, -0.00816702]])

In [45]:
from sklearn import svm
from sklearn.ensemble import AdaBoostClassifier 
from sklearn import tree
from sklearn.neural_network import MLPClassifier

In [46]:
svm_model=svm.SVC()
adaboost_model=AdaBoostClassifier()
decision_tree=tree.DecisionTreeClassifier()
mlp_model=MLPClassifier(hidden_layer_sizes=(10,7,4))

In [47]:
svm_model.fit(X_train,Y_train)

SVC()

In [48]:
adaboost_model.fit(X_train,Y_train)

AdaBoostClassifier()

In [49]:
decision_tree.fit(X_train,Y_train)

DecisionTreeClassifier()

In [50]:
#mlp_model=MLPClassifier(hidden_layer_sizes=(10,8,4))
mlp_model.fit(X_train,Y_train)

MLPClassifier(hidden_layer_sizes=(10, 7, 4))

In [51]:
svm_model.score(X_test,Y_test)

0.9967395440550731

In [52]:
adaboost_model.score(X_test,Y_test)

0.9989621890891479

In [53]:
decision_tree.score(X_test,Y_test)

0.9999308126059432

In [54]:
mlp_model.score(X_test,Y_test)

0.9889559622236829

In [55]:
#now to import the second pcap file as test it
service_scan_csv2_file= os.path.join(here, 'IOT_service_scan_212_0502_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df2=pd.read_csv(service_scan_csv2_file)

In [56]:
df2.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,1392,0x000,1338.0,1338.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000019,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,1167,0x000,1113.0,1113.0,...,127.0,0x00,0x00,NaN,0.000019,0.000019,NaN,NaN,0,NaN
2,0.000023,192.168.100.7,365.0,UDP,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,1,NaN
3,0.000028,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,1295,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.000031,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,1258,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000003,0.000003,0,NaN

In [57]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0,'0x86dd':6}
df2['Protocol']=[protocol_vals[k] for k in df2['Protocol']]

In [58]:
df2['Window']=df2['Window'].fillna(0)
df2['dport']=df2['dport'].fillna(0)
df2['sport']=df2['sport'].fillna(0)
df2['TCP_Flags']=df2['TCP_Flags'].fillna('0x000')
df2['Time to Live']=df2['Time to Live'].fillna(0)
df2['Bytes in flight']=df2['Bytes in flight'].fillna(0)
df2['Time since previous frame(UDP)']=df2['Time since previous frame(UDP)'].fillna(0)
df2['Time since previous frame in this TCP stream(TCP)']=df2['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [59]:
from ast import literal_eval
df2['TCP_Flags']=[literal_eval(k) for k in df2['TCP_Flags']]

In [60]:
X2=df2[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)','Time since previous frame(UDP)']].values
Y2=df2['Attack'].values

In [61]:
df2.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,1392,0,1338.0,1338.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
1,0.000019,192.168.100.55,8080.0,4,192.168.100.3,80.0,1167,0,1113.0,1113.0,...,127.0,0x00,0x00,NaN,0.000019,0.000019,NaN,0.000000,0,NaN
2,0.000023,192.168.100.7,365.0,5,192.168.100.3,565.0,60,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,1,NaN
3,0.000028,192.168.100.46,3456.0,5,192.168.100.5,80.0,1295,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
4,0.000031,192.168.100.5,80.0,5,192.168.100.46,3456.0,1258,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000003,0.000003,0,NaN

In [62]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381640 entries, 0 to 381639
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               381640 non-null  float64
 1   saddr                                              381640 non-null  object
 2   sport                                              381640 non-null  float64
 3   Protocol                                           381640 non-null  int64
 4   daddr                                              381640 non-null  object
 5   dport                                              381640 non-null  float64
 6   Length                                             381640 non-null  int64
 7   TCP_Flags                                          381640 non-null  int64
 8   Bytes in flight                                    381640 non-null  float64
 9   Bytes sent since last PSH flag                     183134 non-null  float64
 10  Window                                             381640 non-null  float64
 11  Time to Live                                       381640 non-null  float64
 12  IPv4_frag_Flags                                    381050 non-null  object
 13  Differentiated Services Field                      381050 non-null  object
 14  The RTT to ACK the segment was                     35396 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     227630 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  381640 non-null  float64
 17  Time since first frame(UDP)                        143556 non-null  float64
 18  Time since previous frame(UDP)                     381640 non-null  float64
 19  Attack                                             381640 non-null  int64
 20  iRTT                                               8820 non-null    float64
dtypes: float64(13), int64(4), object(4)
memory usage: 61.1+ MB

In [65]:
X2

array([[-0.6089108 , -0.20561562, -0.4186281 , ...,  0.54552394,
        -0.03442401, -0.00816702],
       [-0.18161141, -0.62712712, -0.4186281 , ...,  0.37375849,
        -0.0344169 , -0.00816702],
       [-0.59368825, -0.60157299,  1.19802872, ..., -0.47590796,
        -0.03442401, -0.00816702],
       ...,
       [ 1.48378795, -0.60800104, -0.4186281 , ..., -0.47590796,
        -0.01892712, -0.00816702],
       [-0.58952209,  1.43722546, -0.4186281 , ..., -0.35681725,
        -0.03438208, -0.00816702],
       [ 1.48378795, -0.60800104, -0.4186281 , ..., -0.47590796,
        -0.03439722, -0.00816702]])

In [64]:
X2=scaler.transform(X2)

In [66]:
svm_model.score(X2,Y2)

0.9960984173566713

In [67]:
adaboost_model.score(X2,Y2)

0.9976417566292841

In [68]:
decision_tree.score(X2,Y2)

0.9856828424693428

In [69]:
mlp_model.score(X2,Y2)

0.9860680222198931

In [81]:
#testing with third pcap file

service_scan_csv3_file= os.path.join(here, 'IOT_service_scan_211_0502_n.csv')
#exfiltration_csv2_file= os.path.join(here, 'exfiltration_2.csv')

#os_scan_csv=os.path.join(here, 'OS_Scan_labels.csv')

df3=pd.read_csv(service_scan_csv3_file)

In [82]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,TCP,192.168.100.55,8080.0,1444,0x000,1390.0,1390.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000011,192.168.100.55,8080.0,TCP,192.168.100.3,80.0,955,0x000,901.0,901.0,...,127.0,0x00,0x00,NaN,0.000011,0.000011,NaN,NaN,0,NaN
2,0.000013,192.168.100.7,365.0,UDP,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,1,NaN
3,0.000019,192.168.100.46,3456.0,UDP,192.168.100.5,80.0,807,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.5,80.0,UDP,192.168.100.46,3456.0,1327,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000003,0.000003,0,NaN

In [83]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381929 entries, 0 to 381928
Data columns (total 21 columns):
 #   Column                                             Non-Null Count   Dtype
---  ------                                             --------------   -----
 0   Time                                               381929 non-null  float64
 1   saddr                                              381929 non-null  object
 2   sport                                              377103 non-null  float64
 3   Protocol                                           381929 non-null  object
 4   daddr                                              381929 non-null  object
 5   dport                                              377103 non-null  float64
 6   Length                                             381929 non-null  int64
 7   TCP_Flags                                          227989 non-null  object
 8   Bytes in flight                                    183273 non-null  float64
 9   Bytes sent since last PSH flag                     183273 non-null  float64
 10  Window                                             227989 non-null  float64
 11  Time to Live                                       381386 non-null  float64
 12  IPv4_frag_Flags                                    381386 non-null  object
 13  Differentiated Services Field                      381386 non-null  object
 14  The RTT to ACK the segment was                     35819 non-null   float64
 15  Time since first frame in this TCP stream(TCP)     227989 non-null  float64
 16  Time since previous frame in this TCP stream(TCP)  227989 non-null  float64
 17  Time since first frame(UDP)                        143530 non-null  float64
 18  Time since previous frame(UDP)                     143530 non-null  float64
 19  Attack                                             381929 non-null  int64
 20  iRTT                                               8910 non-null    float64
dtypes: float64(13), int64(2), object(6)
memory usage: 61.2+ MB

In [84]:
protocol_vals={'UDP': 5,'TCP':4,'0x0806':3,'':2,'0x8035':1,'IPv4':0,'0x86dd':6}
df3['Protocol']=[protocol_vals[k] for k in df3['Protocol']]

In [85]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,1444,0x000,1390.0,1390.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,NaN,0,NaN
1,0.000011,192.168.100.55,8080.0,4,192.168.100.3,80.0,955,0x000,901.0,901.0,...,127.0,0x00,0x00,NaN,0.000011,0.000011,NaN,NaN,0,NaN
2,0.000013,192.168.100.7,365.0,5,192.168.100.3,565.0,60,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,1,NaN
3,0.000019,192.168.100.46,3456.0,5,192.168.100.5,80.0,807,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.5,80.0,5,192.168.100.46,3456.0,1327,NaN,NaN,NaN,...,127.0,0x00,0x00,NaN,NaN,NaN,0.000003,0.000003,0,NaN

In [86]:
df3['Window']=df3['Window'].fillna(0)
df3['dport']=df3['dport'].fillna(0)
df3['sport']=df3['sport'].fillna(0)
df3['TCP_Flags']=df3['TCP_Flags'].fillna('0x000')
df3['Time to Live']=df3['Time to Live'].fillna(0)
df3['Bytes in flight']=df3['Bytes in flight'].fillna(0)
df3['Time since previous frame(UDP)']=df3['Time since previous frame(UDP)'].fillna(0)
df3['Time since previous frame in this TCP stream(TCP)']=df3['Time since previous frame in this TCP stream(TCP)'].fillna(0)

In [87]:
from ast import literal_eval
df3['TCP_Flags']=[literal_eval(k) for k in df3['TCP_Flags']]

In [88]:
df3.head()

,Time,saddr,sport,Protocol,daddr,dport,Length,TCP_Flags,Bytes in flight,Bytes sent since last PSH flag,...,Time to Live,IPv4_frag_Flags,Differentiated Services Field,The RTT to ACK the segment was,Time since first frame in this TCP stream(TCP),Time since previous frame in this TCP stream(TCP),Time since first frame(UDP),Time since previous frame(UDP),Attack,iRTT
0,0.000000,192.168.100.3,80.0,4,192.168.100.55,8080.0,1444,0,1390.0,1390.0,...,127.0,0x00,0x00,NaN,0.000000,0.000000,NaN,0.000000,0,NaN
1,0.000011,192.168.100.55,8080.0,4,192.168.100.3,80.0,955,0,901.0,901.0,...,127.0,0x00,0x00,NaN,0.000011,0.000011,NaN,0.000000,0,NaN
2,0.000013,192.168.100.7,365.0,5,192.168.100.3,565.0,60,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,1,NaN
3,0.000019,192.168.100.46,3456.0,5,192.168.100.5,80.0,807,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000000,0.000000,0,NaN
4,0.000022,192.168.100.5,80.0,5,192.168.100.46,3456.0,1327,0,0.0,NaN,...,127.0,0x00,0x00,NaN,NaN,0.000000,0.000003,0.000003,0,NaN

In [89]:
X3=df3[['sport','dport','Protocol','Length','Window','TCP_Flags','Bytes in flight','Time since previous frame in this TCP stream(TCP)','Time since previous frame(UDP)']].values
Y3=df3['Attack'].values

In [92]:
X3

array([[-0.6089108 , -0.20561562, -0.4186281 , ...,  0.58522084,
        -0.03442401, -0.00816702],
       [-0.18161141, -0.62712712, -0.4186281 , ...,  0.21191726,
        -0.03441989, -0.00816702],
       [-0.59368825, -0.60157299,  1.19802872, ..., -0.47590796,
        -0.03442401, -0.00816702],
       ...,
       [ 1.48378795, -0.60800104, -0.4186281 , ..., -0.47590796,
        -0.01892712, -0.00816702],
       [-0.58952209,  1.43722546, -0.4186281 , ..., -0.35681725,
        -0.03438208, -0.00816702],
       [ 1.48378795, -0.60800104, -0.4186281 , ..., -0.47590796,
        -0.03439722, -0.00816702]])

In [91]:
X3=scaler.transform(X3)

In [93]:
svm_model.score(X3,Y3)

0.9957007716093829

In [94]:
adaboost_model.score(X3,Y3)

0.9971958138816377

In [95]:
decision_tree.score(X3,Y3)

0.9924540948710362

In [96]:
mlp_model.score(X3,Y3)

0.9872698852404505

In [97]:

import pickle
with open('svm_SERVICE_SCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(svm_model, f)

In [98]:
import pickle
with open('adaboost_SERVICE_SCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(adaboost_model, f)

In [99]:
import pickle
with open('decission_tree_SERVICE_SCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(decision_tree, f)

In [100]:
import pickle
with open('mlp_SERVICE_SCAN_dec08_scaled.pickle', 'wb') as f: 
    pickle.dump(mlp_model, f)